# Meta data
site_name: Causal inference items
copyright: Created by Leo Wu in 2023
repo_url: https://github.com/leowu4ever/causal-inference-items
repo_name: causal inference items

# Page structure
nav: 
- Overview: index.md

# No need to change anything here.
plugins:
  - search
  # third party plugins
  - mkdocs-jupyter:
      ignore_h1_titles: True

# The options below are for manipulating the webpage layout. You don't have to change the below.
# You can follow the guide in https://squidfunk.github.io/mkdocs-material/setup/
theme:
  name: 'material'  # don't remove this line as it tell MkDocs to use Material theme.
  font:
    text: Arial
  # light & dark mode
  palette: 
    - scheme: slate
      primary: pink  # header background color
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        
    - scheme: default
      primary: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.top